#!/usr/bin/env bash

s_arg=$2
app_dir=~/.local/share/totp-cli/
accounts_dir=$app_dir/accounts/

help(){
  echo -e "Usage: totp-cli [OPTION]...\n\nOptions
  \033[32mhelp\033[0m                 show this message
  \033[32minit\033[0m                 initialize the config file
  \033[32mgenerate <account>\033[0m   generate a tokan
  \033[32mnew <account>\033[0m        create new account
  \033[32mremove <account>\033[0m     to remove a specific account
  \033[32mget-secret <account>\033[0m to get a secret to a specific account"
  exit
}
init(){
  if [ -e $app_dir/config ]; then
    printf "\033[31mError:\033[0m config file already exists\n"
    exit
  fi

  [ -e $accounts_dir ] || mkdir -p $accounts_dir
  read -p "GPG Key ID:" GPG_KEY_ID
  echo "GPG_KEY_ID=$GPG_KEY_ID" > $app_dir/config
}
new(){
  [[ $s_arg == "" ]] && help
  if [ -e $accounts_dir/$s_arg ]; then
    printf "\033[31mError:\033[0m key exist\n"
    exit 1;
  fi
  read -p "secret key: " key
  if [[ $key == "" ]]; then
    secret=`pwgen -1 16`
    echo $secret | base32 | gpg -e -r $GPG_KEY_ID  > $accounts_dir/$s_arg
    echo "secret: $secret"
  else
    echo $key | gpg -e -r $GPG_KEY_ID  > $accounts_dir/$s_arg
  fi
  [ $? == 0 ] && echo key got generated
}
generate(){
  [[ $s_arg == "" ]] && s_arg=`ls $accounts_dir/ | fzf`
  key=`gpg -d $accounts_dir/$s_arg 2> /dev/null |cut -f 1 -d ' '`
  [[ $? != "0" ]] && exit
  oathtool --totp -b -d 6 $key
}
get_secret(){
  [[ $s_arg == "" ]] && s_arg=`ls $accounts_dir/ | fzf`
  key=`gpg -d $accounts_dir/$s_arg 2> /dev/null |cut -f 1 -d ' '`
  echo $key;
}
remove(){
  [[ $s_arg == "" ]] && s_arg=`ls $accounts_dir/ | fzf`
  read -p "Are you sure you want to remove this account? [N/y] " confirmation
  confirmation=`echo $confirmation | tr "[:upper:]" "[:lower:]"`
  if [[ $confirmation == "y" || $confirmation == "yes" ]]; then
    rm $accounts_dir/$s_arg
  fi
}
if [ ! -e $app_dir/config ]; then
  init
  exit
else
  source $app_dir/config
fi

case $1 in
  "init")
    init ;;
  "generate")
    generate ;;
  "new")
    new ;;
  "remove")
    remove ;;
  "get-secret")
    get_secret ;;
  "help")
    help ;;
  *)
    help ;;
esac
